############################################################
# Marketing Analytics
# Week 13: Customer Lifetime Value (CLV)
#
# Purpose of this script:
# This script introduces Customer Lifetime Value (CLV),
# simple retention-style analysis, and marketing strategy
# implications using transaction-level retail data.
#
# Students will learn how to:
# 1. Clean transaction data
# 2. Calculate basic customer-level metrics
# 3. Estimate historical CLV
# 4. Build a simple repeat-purchase / retention indicator
# 5. Interpret customer value for marketing strategy
############################################################



############################################################
# 1. Load Required Packages
############################################################

# Install packages if needed
# install.packages("tidyverse")
# install.packages("lubridate")

library(tidyverse)
library(lubridate)



############################################################
# 2. Import Dataset
############################################################

# Load the Online Retail dataset
# If using the UCI file in CSV form, update the file name as needed
data <- read.csv("OnlineRetail.csv", stringsAsFactors = FALSE)

# Inspect the data
head(data)
str(data)
summary(data)



############################################################
# 3. Basic Data Cleaning
############################################################

# Convert InvoiceDate to date-time format
data$InvoiceDate <- mdy_hms(data$InvoiceDate)

# Remove rows with missing CustomerID
data <- data %>%
  filter(!is.na(CustomerID),
         CustomerID != "")

# Remove cancelled transactions
# In this dataset, InvoiceNo starting with "C" indicates cancellations
data <- data %>%
  filter(substr(InvoiceNo, 1, 1) != "C")

# Remove negative or zero quantity and price
data <- data %>%
  filter(Quantity > 0,
         UnitPrice > 0)

# Create transaction revenue
data <- data %>%
  mutate(revenue = Quantity * UnitPrice)

head(data)



############################################################
# 4. Create Customer-Level Summary Metrics
############################################################

# Find the end of the observation period
analysis_date <- max(data$InvoiceDate) + days(1)

# Calculate customer-level metrics
customer_summary <- data %>%
  group_by(CustomerID) %>%
  summarize(
    first_purchase = min(InvoiceDate),
    last_purchase = max(InvoiceDate),
    frequency = n_distinct(InvoiceNo),
    total_revenue = sum(revenue),
    avg_order_value = total_revenue / frequency,
    recency_days = as.numeric(difftime(analysis_date, last_purchase, units = "days")),
    customer_age_days = as.numeric(difftime(analysis_date, first_purchase, units = "days"))
  )

head(customer_summary)
summary(customer_summary)



############################################################
# 5. CLV Calculation Methods
############################################################

# Method 1: Historical CLV
# Historical CLV = total revenue generated by the customer so far
customer_summary <- customer_summary %>%
  mutate(historical_clv = total_revenue)

# Method 2: Simple forward-looking CLV approximation
# Approximate CLV = average order value * purchase frequency
customer_summary <- customer_summary %>%
  mutate(simple_clv = avg_order_value * frequency)

# View top customers
customer_summary %>%
  arrange(desc(historical_clv)) %>%
  head(10)



############################################################
# 6. Distribution of CLV
############################################################

# Histogram of historical CLV
hist(customer_summary$historical_clv,
     main = "Distribution of Historical CLV",
     xlab = "Historical CLV",
     col = "lightblue",
     border = "white")

# Boxplot of CLV
boxplot(customer_summary$historical_clv,
        main = "Boxplot of Historical CLV",
        ylab = "Historical CLV",
        col = "orange")



############################################################
# 7. Retention Modeling (Simple Repeat-Purchase Indicator)
############################################################

# Create a simple retention indicator:
# retained = customer made more than one purchase
customer_summary <- customer_summary %>%
  mutate(retained = ifelse(frequency > 1, 1, 0))

table(customer_summary$retained)

# Another useful indicator:
# at-risk customers = high recency (haven't purchased recently)
customer_summary <- customer_summary %>%
  mutate(at_risk = ifelse(recency_days > median(recency_days), 1, 0))

table(customer_summary$at_risk)



############################################################
# 8. Logistic Regression for Retention
############################################################

# Predict whether a customer is retained based on
# recency, average order value, and customer age
retention_model <- glm(retained ~ recency_days + avg_order_value + customer_age_days,
                       data = customer_summary,
                       family = binomial)

summary(retention_model)

# Odds ratios
exp(coef(retention_model))



############################################################
# 9. Predict Retention Probability
############################################################

customer_summary$predicted_retention <- predict(retention_model,
                                                newdata = customer_summary,
                                                type = "response")

head(customer_summary %>%
       select(CustomerID, retained, predicted_retention, historical_clv))



############################################################
# 10. Customer Value Segmentation
############################################################

# Create CLV groups based on quartiles
customer_summary <- customer_summary %>%
  mutate(clv_group = ntile(historical_clv, 4))

table(customer_summary$clv_group)

# Label the groups
customer_summary$clv_group <- factor(customer_summary$clv_group,
                                     levels = c(1, 2, 3, 4),
                                     labels = c("Low Value",
                                                "Medium-Low Value",
                                                "Medium-High Value",
                                                "High Value"))

table(customer_summary$clv_group)



############################################################
# 11. Marketing Strategy Implications
############################################################

# Compare average metrics by CLV group
customer_summary %>%
  group_by(clv_group) %>%
  summarize(
    customers = n(),
    avg_historical_clv = mean(historical_clv),
    avg_frequency = mean(frequency),
    avg_order_value = mean(avg_order_value),
    avg_recency_days = mean(recency_days),
    retention_rate = mean(retained)
  )

# Visualize retention probability by CLV group
ggplot(customer_summary, aes(x = clv_group, y = predicted_retention)) +
  geom_boxplot() +
  labs(title = "Predicted Retention by CLV Group",
       x = "CLV Group",
       y = "Predicted Retention Probability")

# Visualize historical CLV by retention status
ggplot(customer_summary, aes(x = factor(retained), y = historical_clv)) +
  geom_boxplot() +
  labs(title = "Historical CLV by Retention Status",
       x = "Retained (0 = No, 1 = Yes)",
       y = "Historical CLV")



############################################################
# 12. Interpretation Notes
############################################################

# Example questions for students:
# - Which customers generate the most value?
# - Are high-CLV customers also more likely to be retained?
# - Which customers appear to be at risk of churn?
# - How should a firm prioritize retention spending?



############################################################
# 13. Optional: Save Customer Summary File
############################################################

# write.csv(customer_summary,
#           "customer_clv_summary.csv",
#           row.names = FALSE)



############################################################
# End of Week 13 Script
#
# Students should now be able to:
# - Calculate historical CLV
# - Build a simple retention model
# - Interpret customer value for marketing decisions
# - Translate analytics into retention strategy
############################################################